version: "3.8"

services:
  web:
    build: .
    container_name: pdfqa_web
    command: conda run --no-capture-output -n myenv gunicorn PDF_QA.wsgi --workers 3 --worker-class gevent --timeout 120 --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery:
    build: .
    container_name: celery_worker
    command: conda run --no-capture-output -n myenv celery -A PDF_QA worker --loglevel=info --pool=solo --max-tasks-per-child=5
    depends_on:
      - redis
      - web
    env_file:
      - .env
    restart: always

  redis:
    image: redis:alpine
    container_name: pdfqa_redis
    ports:
      - "6379:6379"
    restart: always
