# Generated by Django 5.2.1 on 2025-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferalPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_id", models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name="Ans_pdf",
        ),
    ]
